# This is a basic workflow to help you get started with Actions

name: Run CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: fabric8/java-alpine-openjdk11-jre:1.9.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
        
      - name: Build with Maven
        run: mvn clean package --file pom.xml
        
  deploy:
    runs-on: fabric8/java-alpine-openjdk11-jre:1.9.0
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
          name: jar-artifact
          path: target/
    - name: Docker build
      run: |
        docker build . -t indojapcorp/knote-java:${{needs.build.outputs.jar_version}}
  #  - name: Login to DockerHub
  #    uses: docker/login-action@v1
  #    with:
  #      username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #  - name: Docker push
  #    run: |
  #      docker push indojapcorp/knote-java:${{needs.build.outputs.jar_version}}

  #run:
  #    runs-on: fabric8/java-alpine-openjdk11-jre:1.9.0
  #    needs: [build, deploy]

  #    steps:
  #      - name: Run container
  #        run: |
  #          docker run indojapcorp/knote-java:${{needs.build.outputs.jar_version}}

      
